name = "TreeArrays"
uuid = "c171eb22-09ea-4e91-ac0c-64a4bcedb176"
authors = ["Keita Nakamura <keita.nakamura.1109@gmail.com>"]
version = "0.1.0"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
